### ISSUE TITLE
idea: maybe more complete discord-ipc implementation

### ISSUE THREAD

**Issue by DjDeveloperr** [littledivy/discordrpc_deno#1]
As Discord RPC protocol is not just limited to Rich Presence, are there any plans to add support for things like OAuth2, Events, etc.? I'd be willing to contribute such.

**Comment by littledivy** [comment]
accepting contributions, lets add 'em :+1:

**Comment by DjDeveloperr** [comment]
The API is pretty much complete, it should be possible to use all rpc commands now. Closing this issue
